spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/health_clinic_db
    username: postgres
    password: Nji90okm.
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    enabled: true
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect